# docker-compose.yml
version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://usuario:contraseña@db:5432/mi_base
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: mi_base
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

